# Generated by Django 2.2.7 on 2020-01-10 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
