# Generated by Django 2.2.7 on 2020-01-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('clinic', models.CharField(choices=[('Ajmer', 'Ajmer')], max_length=100)),
                ('time', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=100)),
                ('amount', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
