# Generated by Django 2.2.7 on 2020-01-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='amount',
            field=models.CharField(choices=[(100, 100)], max_length=100),
        ),
    ]
