# Generated by Django 3.1.5 on 2021-02-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200112_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='amount',
            field=models.CharField(choices=[('100 Rupees', 100)], max_length=100),
        ),
    ]
